package model;

public enum Permission {
	CREATE_CAMP,
    MODIFY_CAMP, 
    SUGGEST_CAMP,
    APPROVE_SUGGEST,
    VIEW_CAMPS, 
    VIEW_CAMPS_SUPER,
    VIEW_CAMP,
    ENQUIRY,
    VIEW_ENQUIRIES,
    RESOLVE_ENQUIRY,
}